api_key: "<your-api-key>"
# api_base_url: ""
model_name: "<model-name>"
agent_name: "FinBot-7"
max_tokens: 8192
temperature: 0.6
max_retries: 20
max_rounds: 10
system_prompt_file: "prompts/financial_manager.json"
save_conversation_file: "../results/financial_manager/<model-name>.json"